import fs from "node:fs";
import path from "node:path";

const packageRoot = path.resolve(import.meta.dirname, "..");
const repoRoot = path.resolve(packageRoot, "..", "..");
const openapiPath = path.join(repoRoot, "docs", "api", "openapi.yaml");
const outputPath = path.join(packageRoot, "src", "generated", "openapi_types.rs");
const methodNames = new Set(["get", "post", "put", "patch", "delete"]);

export function extractOperations() {
  const lines = fs.readFileSync(openapiPath, "utf8").split(/\r?\n/);
  const operations = [];
  let currentPath = null;
  let currentPathIndent = 0;

  for (const line of lines) {
    if (line === "components:") {
      break;
    }
    const pathMatch = line.match(/^(  )\"?(\/api\/v1\/[^\":]+)\"?:\s*$/);
    if (pathMatch) {
      currentPath = pathMatch[2];
      currentPathIndent = pathMatch[1].length;
      continue;
    }

    const methodMatch = line.match(/^(\s*)(get|post|put|patch|delete):\s*$/);
    if (currentPath && methodMatch && methodMatch[1].length > currentPathIndent && methodNames.has(methodMatch[2])) {
      operations.push({ method: methodMatch[2].toUpperCase(), path: currentPath });
    }
  }

  const seen = new Set();
  const unique = [];
  for (const operation of operations) {
    const key = `${operation.method} ${operation.path}`;
    if (!seen.has(key)) {
      seen.add(key);
      unique.push(operation);
    }
  }
  unique.sort((a, b) => `${a.method} ${a.path}`.localeCompare(`${b.method} ${b.path}`));
  return unique;
}

export function renderOpenApiTypes() {
  const operations = extractOperations();
  const rows = operations
    .map((operation) => `    TreeDxOpenApiOperation {\n        method: "${operation.method}",\n        path: "${operation.path}",\n    },`)
    .join("\n");

  return `// Generated by scripts/generate_treedx_openapi_types.ts. Do not edit by hand.\n\n#[derive(Clone, Copy, Debug, Eq, PartialEq)]\npub struct TreeDxOpenApiOperation {\n    pub method: &'static str,\n    pub path: &'static str,\n}\n\npub const TREEDX_OPENAPI_OPERATION_COUNT: usize = ${operations.length};\n\npub const TREEDX_OPENAPI_OPERATIONS: &[TreeDxOpenApiOperation] = &[\n${rows}\n];\n`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === new URL(import.meta.url).pathname) {
  fs.writeFileSync(outputPath, renderOpenApiTypes(), "utf8");
}
