import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import YAML from "yaml";

const packageRoot = path.resolve(import.meta.dirname, "..");
const repoRoot = path.resolve(packageRoot, "..", "..");
const openapiPath = path.join(repoRoot, "docs", "api", "openapi.yaml");
const outputPath = path.join(packageRoot, "src", "treedx", "generated", "openapi-types.ts");
const contractOutputPath = path.join(packageRoot, "src", "treedx", "openapi", "contract.ts");
const packagedOpenapiPath = path.join(packageRoot, "openapi.yaml");
const packagedContractPath = path.join(packageRoot, "openapi-contract.json");

function sha256(value) {
  return `sha256:${crypto.createHash("sha256").update(value).digest("hex")}`;
}

function readContractSource() {
  const source = fs.readFileSync(openapiPath, "utf8");
  const openapi = YAML.parse(source);
  const operations = [];

  for (const [apiPath, methods] of Object.entries(openapi.paths ?? {})) {
    if (!apiPath.startsWith("/api/v1/")) continue;
    for (const [method, definition] of Object.entries(methods)) {
      const requiredCapabilities = Array.isArray(definition?.["x-treedx-required-capabilities"])
        ? definition["x-treedx-required-capabilities"].map(String).sort()
        : [];
      operations.push({ method: method.toUpperCase(), operationId: String(definition?.operationId ?? ""), path: apiPath, requiredCapabilities });
    }
  }

  operations.sort((left, right) => `${left.method} ${left.path}`.localeCompare(`${right.method} ${right.path}`));
  return { source, openapi, operations };
}

export function renderOpenApiTypes() {
  const { operations } = readContractSource();
  const operationLiterals = operations
    .map((operation) => `  { method: "${operation.method}", operationId: "${operation.operationId}", path: "${operation.path}", requiredCapabilities: ${JSON.stringify(operation.requiredCapabilities)} }`)
    .join(",\n");

  return `// Generated by scripts/generate-treedx-openapi-types.ts. Do not edit by hand.\n\nexport type TreeDxOpenApiMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";\n\nexport interface TreeDxOpenApiOperation {\n  method: TreeDxOpenApiMethod;\n  operationId: string;\n  path: string;\n  requiredCapabilities: readonly string[];\n}\n\nexport type TreeDxOpenApiPath = typeof TREEDX_OPENAPI_OPERATIONS[number]["path"];\nexport type TreeDxOpenApiOperationId = typeof TREEDX_OPENAPI_OPERATIONS[number]["operationId"];\nexport type TreeDxOpenApiOperationKey = \`${"${TreeDxOpenApiMethod} ${TreeDxOpenApiPath}"}\`;\n\nexport const TREEDX_OPENAPI_OPERATION_COUNT = ${operations.length} as const;\n\nexport const TREEDX_OPENAPI_OPERATIONS = [\n${operationLiterals}\n] as const satisfies readonly TreeDxOpenApiOperation[];\n`;
}

export function renderOpenApiContractArtifacts() {
  const { source, openapi, operations } = readContractSource();
  const generatedTypes = renderOpenApiTypes();
  const inventory = operations.map(({ method, operationId, path: apiPath, requiredCapabilities }) => ({ method, operationId, path: apiPath, requiredCapabilities }));
  const contract = {
    schema: "treedx.openapi-contract/v1",
    packageVersion: "0.3.0-rc.1",
    openapiVersion: String(openapi.info?.version ?? ""),
    openapiSha256: sha256(source),
    operationInventorySha256: sha256(JSON.stringify(inventory)),
    generatedTypesSha256: sha256(generatedTypes),
    operationCount: inventory.length,
    compatibility: "breaking-prerelease",
  };
  return {
    contractJson: `${JSON.stringify(contract, null, 2)}\n`,
    contractTypescript: `// Generated by scripts/generate-treedx-openapi-types.ts. Do not edit by hand.\n\nexport const TREEDX_OPENAPI_CONTRACT = ${JSON.stringify(contract, null, 2)} as const;\n`,
    openapiSource: source,
  };
}

if (process.argv[1] && path.resolve(process.argv[1]) === new URL(import.meta.url).pathname) {
  fs.writeFileSync(outputPath, renderOpenApiTypes(), "utf8");
  const artifacts = renderOpenApiContractArtifacts();
  fs.mkdirSync(path.dirname(contractOutputPath), { recursive: true });
  fs.writeFileSync(contractOutputPath, artifacts.contractTypescript, "utf8");
  fs.writeFileSync(packagedOpenapiPath, artifacts.openapiSource, "utf8");
  fs.writeFileSync(packagedContractPath, artifacts.contractJson, "utf8");
}
