defmodule TreeDx.Env do
  @moduledoc false

  @aliases %{
    "SECRET_KEY_BASE" => "TREESEED_TREEDX_SECRET_KEY_BASE",
    "TREEDX_ALLOW_DEV_VERIFIER_IN_PROD" => "TREESEED_TREEDX_ALLOW_DEV_VERIFIER_IN_PROD",
    "TREEDX_AUTH_MODE" => "TREESEED_TREEDX_AUTH_MODE",
    "TREEDX_AUTH_VERIFIER" => "TREESEED_TREEDX_AUTH_VERIFIER",
    "TREEDX_ALLOW_DIRECT_EXEC_IN_PROD" => "TREESEED_TREEDX_ALLOW_DIRECT_EXEC_IN_PROD",
    "TREEDX_BOOTSTRAP_TRUST_ACTOR_ID" => "TREESEED_TREEDX_BOOTSTRAP_TRUST_ACTOR_ID",
    "TREEDX_BOOTSTRAP_TRUST_CAPABILITIES" => "TREESEED_TREEDX_BOOTSTRAP_TRUST_CAPABILITIES",
    "TREEDX_BOOTSTRAP_TRUST_PATHS" => "TREESEED_TREEDX_BOOTSTRAP_TRUST_PATHS",
    "TREEDX_BOOTSTRAP_TRUST_REFS" => "TREESEED_TREEDX_BOOTSTRAP_TRUST_REFS",
    "TREEDX_BOOTSTRAP_TRUST_REPO_IDS" => "TREESEED_TREEDX_BOOTSTRAP_TRUST_REPO_IDS",
    "TREEDX_BOOTSTRAP_TRUST_TENANT_ID" => "TREESEED_TREEDX_BOOTSTRAP_TRUST_TENANT_ID",
    "TREEDX_DATA_DIR" => "TREESEED_TREEDX_DATA_DIR",
    "TREEDX_ENV" => "TREESEED_TREEDX_ENV",
    "TREEDX_EXEC_BACKEND" => "TREESEED_TREEDX_EXEC_BACKEND",
    "TREEDX_EXEC_WORKER_HMAC_SECRET" => "TREESEED_TREEDX_EXEC_WORKER_HMAC_SECRET",
    "TREEDX_EXEC_WORKER_TOKEN" => "TREESEED_TREEDX_EXEC_WORKER_TOKEN",
    "TREEDX_EXEC_WORKER_URL" => "TREESEED_TREEDX_EXEC_WORKER_URL",
    "TREEDX_GIT_EXTERNAL_TRANSPORT_ENABLED" => "TREESEED_TREEDX_GIT_EXTERNAL_TRANSPORT_ENABLED",
    "TREEDX_GIT_SSH_ENABLED" => "TREESEED_TREEDX_GIT_SSH_ENABLED",
    "TREEDX_GIT_SSH_KNOWN_HOSTS" => "TREESEED_TREEDX_GIT_SSH_KNOWN_HOSTS",
    "TREEDX_JWKS_URL" => "TREESEED_TREEDX_JWKS_URL",
    "TREEDX_JWT_ALLOWED_ALGS" => "TREESEED_TREEDX_JWT_ALLOWED_ALGS",
    "TREEDX_JWT_AUDIENCE" => "TREESEED_TREEDX_JWT_AUDIENCE",
    "TREEDX_JWT_CLOCK_SKEW_SECONDS" => "TREESEED_TREEDX_JWT_CLOCK_SKEW_SECONDS",
    "TREEDX_JWT_HS256_SECRET" => "TREESEED_TREEDX_JWT_HS256_SECRET",
    "TREEDX_JWT_ISSUER" => "TREESEED_TREEDX_JWT_ISSUER",
    "TREEDX_REMOTE_CREDENTIAL_PROVIDER" => "TREESEED_TREEDX_REMOTE_CREDENTIAL_PROVIDER",
    "TREEDX_STORAGE_RESTORE_ACK" => "TREESEED_TREEDX_STORAGE_RESTORE_ACK",
    "TREEDX_STORAGE_RESTORE_ENABLED" => "TREESEED_TREEDX_STORAGE_RESTORE_ENABLED",
    "TREEDX_TREESEED_API_BASE_URL" => "TREESEED_TREEDX_API_BASE_URL",
    "TREEDX_TREESEED_GITHUB_INSTALLATION_ID" => "TREESEED_TREEDX_GITHUB_INSTALLATION_ID",
    "TREEDX_TREESEED_PROJECT_ID" => "TREESEED_TREEDX_PROJECT_ID",
    "TREEDX_TREESEED_REPOSITORY" => "TREESEED_TREEDX_REPOSITORY",
    "TREEDX_TREESEED_SERVICE_ID" => "TREESEED_TREEDX_SERVICE_ID",
    "TREEDX_TREESEED_SERVICE_SECRET" => "TREESEED_TREEDX_SERVICE_SECRET",
    "TREEDX_TREESEED_TEAM_ID" => "TREESEED_TREEDX_TEAM_ID"
  }

  def get(name, default \\ nil) when is_binary(name) do
    case prefixed(name) do
      nil -> System.get_env(name) || default
      prefixed_name -> System.get_env(prefixed_name) || System.get_env(name) || default
    end
  end

  def normalize(env) when is_map(env) do
    Enum.reduce(@aliases, env, fn {legacy, prefixed}, acc ->
      cond do
        present?(Map.get(acc, legacy)) ->
          acc

        present?(Map.get(acc, prefixed)) ->
          Map.put(acc, legacy, Map.get(acc, prefixed))

        true ->
          acc
      end
    end)
  end

  def apply_prefixed_aliases! do
    Enum.each(@aliases, fn {legacy, prefixed} ->
      if !present?(System.get_env(legacy)) and present?(System.get_env(prefixed)) do
        System.put_env(legacy, System.get_env(prefixed))
      end
    end)
  end

  defp prefixed(name), do: Map.get(@aliases, name)

  defp present?(value), do: is_binary(value) and String.trim(value) != ""
end
