// Generated by scripts/generate-treedx-openapi-types.ts. Do not edit by hand.

export const TREEDX_OPENAPI_CONTRACT = {
  "schema": "treedx.openapi-contract/v1",
  "packageVersion": "0.3.0-rc.3",
  "openapiVersion": "0.11.0",
  "openapiSha256": "sha256:52ed190300922c388b115981e60635c306c643d48a3308ef9f79975510ae1926",
  "operationInventorySha256": "sha256:bcfaa9233fcfe7fb49dd0807f08105b3e4056e07ffc8a5dd890e5ec27f975764",
  "generatedTypesSha256": "sha256:505c89e5a0778f79853d8ab652e1a5f8d1bb1fcf2c135571be4972fc3326166e",
  "operationCount": 119,
  "compatibility": "breaking-prerelease"
} as const;
