// Generated by scripts/generate-treedx-openapi-types.ts. Do not edit by hand.

export const TREEDX_OPENAPI_CONTRACT = {
  "schema": "treedx.openapi-contract/v1",
  "packageVersion": "0.3.0-rc.18",
  "openapiVersion": "0.11.1",
  "openapiSha256": "sha256:d7428e2451e63ba1981bdd2aaad981f0a655d6c4fe860e4a27b61e8aa06cbb39",
  "operationInventorySha256": "sha256:9c8b18ae0ac3c645ba62b17fb03c6573941e13264d8459ae1451fc892f1f784b",
  "generatedTypesSha256": "sha256:60ef44398275b7acd2a88555a448b69e4a410deebd884e86cc35754af6dff72c",
  "operationCount": 120,
  "compatibility": "breaking-prerelease"
} as const;
