defmodule TreeDxSdk.OpenApiGenerator do
  @openapi_path Path.expand("../../../docs/api/openapi.yaml", __DIR__)
  @output_path Path.expand("../lib/treedx_sdk/generated/openapi_types.ex", __DIR__)

  def operations do
    @openapi_path
    |> File.read!()
    |> String.split("\n")
    |> extract([], nil, 0)
    |> Enum.uniq()
    |> Enum.sort_by(fn {method, path} -> method <> " " <> path end)
  end

  def render do
    rows =
      operations()
      |> Enum.map(fn {method, path} ->
        "    %{\n      method: #{inspect(method)},\n      path: #{inspect(path)}\n    }"
      end)
      |> Enum.join(",\n")

    """
    # Generated by scripts/generate_treedx_openapi_types.exs. Do not edit by hand.

    defmodule TreeDxSdk.Generated.OpenApiTypes do
      @operation_count #{length(operations())}

      @operations [
    #{rows}
      ]

      def operation_count, do: @operation_count
      def operations, do: @operations
    end
    """
  end

  def write!, do: File.write!(@output_path, render())

  defp extract([], acc, _path, _indent), do: Enum.reverse(acc)
  defp extract(["components:" <> _ | _], acc, _path, _indent), do: Enum.reverse(acc)

  defp extract([line | rest], acc, path, indent) do
    cond do
      match = Regex.run(~r/^(  )\"?(\/api\/v1\/[^\":]+)\"?:\s*$/, line) ->
        [_full, spaces, next_path] = match
        extract(rest, acc, next_path, String.length(spaces))

      match = Regex.run(~r/^(\s*)(get|post|put|patch|delete):\s*$/, line) ->
        [_full, spaces, method] = match

        acc =
          if path && String.length(spaces) > indent,
            do: [{String.upcase(method), path} | acc],
            else: acc

        extract(rest, acc, path, indent)

      true ->
        extract(rest, acc, path, indent)
    end
  end
end

expected = TreeDxSdk.OpenApiGenerator.render()
actual = File.read!(Path.expand("../lib/treedx_sdk/generated/openapi_types.ex", __DIR__))

if actual == expected do
  IO.puts("TreeDX generated OpenAPI metadata is fresh")
else
  IO.puts(
    :stderr,
    "TreeDX generated OpenAPI metadata is stale. Run mix run scripts/generate_treedx_openapi_types.exs."
  )

  System.halt(1)
end
