from __future__ import annotations

from pathlib import Path
import re


PACKAGE_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = PACKAGE_ROOT.parents[1]
OPENAPI_PATH = REPO_ROOT / "docs" / "api" / "openapi.yaml"
OUTPUT_PATH = PACKAGE_ROOT / "src" / "treedx_sdk" / "generated" / "openapi_types.py"


def render_openapi_types() -> str:
    operation_keys: set[tuple[str, str]] = set()
    current_path: str | None = None
    in_paths = False
    for line in OPENAPI_PATH.read_text(encoding="utf8").splitlines():
        if line == "paths:":
            in_paths = True
            continue
        if in_paths and line and not line.startswith(" "):
            break
        if not in_paths:
            continue
        path_match = re.match(r"^  (/api/v1/[^:]+):\s*$", line)
        if path_match:
            current_path = path_match.group(1)
            continue
        method_match = re.match(r"^    (get|post|put|patch|delete):\s*$", line)
        if current_path and method_match:
            operation_keys.add((method_match.group(1).upper(), current_path))
    operations = [{"method": method, "path": path} for method, path in operation_keys]
    operations.sort(key=lambda operation: f"{operation['method']} {operation['path']}")
    rendered_operations = ",\n".join(
        f"    {{\"method\": \"{operation['method']}\", \"path\": \"{operation['path']}\"}}"
        for operation in operations
    )
    return (
        "# Generated by scripts/generate_treedx_openapi_types.py. Do not edit by hand.\n\n"
        "from typing import Final, Literal, TypedDict\n\n\n"
        "TreeDxOpenApiMethod = Literal[\"GET\", \"POST\", \"PUT\", \"PATCH\", \"DELETE\"]\n\n\n"
        "class TreeDxOpenApiOperation(TypedDict):\n"
        "    method: TreeDxOpenApiMethod\n"
        "    path: str\n\n\n"
        f"TREEDX_OPENAPI_OPERATION_COUNT: Final[int] = {len(operations)}\n\n"
        "TREEDX_OPENAPI_OPERATIONS: Final[tuple[TreeDxOpenApiOperation, ...]] = (\n"
        f"{rendered_operations}\n"
        ")\n"
    )


def main() -> None:
    OUTPUT_PATH.write_text(render_openapi_types(), encoding="utf8")


if __name__ == "__main__":
    main()
